"""Tests for the bundled COR IIT projections and their refresh parser."""
from __future__ import annotations

import json

import pytest

from census_forecaster.cor import (
    DATA_PATH,
    cor_source_url,
    cor_vintage,
    load_cor_iit_projections,
)
from census_forecaster.scripts.refresh_cor_iit import (
    RefreshError,
    find_latest_attachment,
    parse_iit_row,
)

pytestmark = pytest.mark.smoke


# A trimmed copy of the real May 21, 2026 attachment text.
SAMPLE = """ESTIMATES OF GENERAL FUND TAX REVENUE FROM THE MEETING OF MAY 21, 2026: FY 2026 TO FY 2032
Line item projections generated by Tax Research & Planning Office
(in thousands of dollars)
BASE ESTIMATED
TYPE OF TAX FY 2024 FY 2025 FY 2026 FY 2027 FY 2028 FY 2029 FY 2030 FY 2031 FY 2032
General Excise and Use Tax $4,446,125 $4,596,199 $4,726,464 $4,930,355 $5,154,355 $5,345,908 $5,537,207 $5,693,084 $5,844,759
Individual Income Tax 3,280,416 3,288,541 3,139,079 2,923,065 2,874,134 2,872,305 2,780,166 2,881,860 2,971,795
Corporate Income Tax 483,676 400,097 420,940 456,924 424,381 435,006 470,497 480,940 500,507
GENERAL FUND TOTAL $9,568,313 $9,974,161 $9,724,807 $9,822,055 $10,008,674 $10,258,891 $10,443,551 $10,767,301 $11,133,389
"""


def test_parses_iit_row_into_millions():
    got = parse_iit_row(SAMPLE)
    assert got[2026] == pytest.approx(3_139.079)
    assert got[2032] == pytest.approx(2_971.795)
    assert len(got) == 9


def test_column_mismatch_raises_rather_than_guessing():
    """A row with fewer numbers than FY columns must fail loudly.

    Silently zipping a short row would misalign every year and produce a
    plausible-looking but wrong scale factor.
    """
    broken = SAMPLE.replace(
        "Individual Income Tax 3,280,416 3,288,541 3,139,079 "
        "2,923,065 2,874,134 2,872,305 2,780,166 2,881,860 2,971,795",
        "Individual Income Tax 3,280,416 3,288,541 3,139,079",
    )
    with pytest.raises(RefreshError, match="column mismatch"):
        parse_iit_row(broken)


def test_missing_iit_row_raises():
    with pytest.raises(RefreshError, match="Individual Income Tax"):
        parse_iit_row(SAMPLE.replace("Individual Income Tax", "Some Other Tax"))


def test_missing_header_raises():
    with pytest.raises(RefreshError, match="header"):
        parse_iit_row(SAMPLE.replace("TYPE OF TAX", "KINDS OF TAX"))


def test_find_latest_attachment_picks_newest_meeting():
    html = """
      <a href="/tax/useful/cor/2026gf01-07_attach_1.pdf">Attachment 1</a>
      <a href="/tax/useful/cor/2026gf05-21_attach_1.pdf">Attachment 1</a>
      <a href="/tax/useful/cor/2026gf03-10_attach_1.pdf">Attachment 1</a>
    """
    url, meeting = find_latest_attachment(html)
    assert meeting.isoformat() == "2026-05-21"
    assert url.endswith("2026gf05-21_attach_1.pdf")


def test_find_latest_attachment_ignores_tpi_meetings():
    """TPI meetings carry no General Fund line items — must not be selected."""
    html = """
      <a href="/tax/useful/cor/2026gf05-21_attach_1.pdf">GF</a>
      <a href="/tax/useful/cor/2026tpi07-30_attach_1.pdf">TPI</a>
    """
    url, meeting = find_latest_attachment(html)
    assert meeting.isoformat() == "2026-05-21"
    assert "tpi" not in url


def test_find_latest_attachment_raises_when_layout_changes():
    with pytest.raises(RefreshError, match="layout"):
        find_latest_attachment("<a href='/nothing/relevant.pdf'>x</a>")


def test_bundled_data_file_is_present_and_sane():
    assert DATA_PATH.exists(), "run scripts.refresh_cor_iit to generate it"
    payload = json.loads(DATA_PATH.read_text())
    assert payload["units"] == "$M"
    assert payload["fy_to_ty_convention"] == "FY(n+1) = TY(n)"
    assert payload["source_url"].startswith("https://files.hawaii.gov/")


def test_tax_year_keys_are_fiscal_year_minus_one():
    by_fy = load_cor_iit_projections(by="fiscal_year")
    by_ty = load_cor_iit_projections(by="tax_year")
    assert {fy - 1 for fy in by_fy} == set(by_ty)
    for fy, v in by_fy.items():
        assert by_ty[fy - 1] == v


def test_projections_cover_the_forecast_window():
    by_ty = load_cor_iit_projections()
    for year in (2027, 2028, 2029, 2030, 2031):
        assert year in by_ty, f"COR data missing TY{year}"
        assert 1_000.0 < by_ty[year] < 10_000.0, "IIT projection outside sane $M range"


def test_vintage_is_at_least_the_may_2026_forecast():
    """Guard against a refresh silently regressing to an older meeting."""
    assert cor_vintage() >= "2026-05-21"
    assert cor_source_url().endswith(".pdf")


def test_invalid_by_argument_rejected():
    with pytest.raises(ValueError, match="tax_year"):
        load_cor_iit_projections(by="calendar_year")


def test_tax_modeler_consumes_the_bundled_vintage():
    """The scale-factor table must be the bundled data, not a stale literal.

    Skipped where tax_modeler isn't installed: the refresh-data workflow's
    smoke gate installs only the census-forecaster package and runs exactly
    this directory, so an unguarded import would fail that job.
    """
    qa = pytest.importorskip(
        "tax_modeler.scenarios.quintile_analysis",
        reason="tax_modeler not installed (census-forecaster-only environment)",
    )
    assert qa.DEFAULT_COR_IIT_PROJECTIONS_M == load_cor_iit_projections()
