"""Donor-matching imputation (CPS-ASEC → ACS PUMS).

ACS PUMS lacks several variables that the SPM resource calculation
needs for full Census P60-280 fidelity:

* **MOOP** (medical out-of-pocket expenses) — needed to subtract from
  resources. Currently zeroed in :func:`tax_modeler.poverty.compute_spm_resources`.
* **Childcare expenses paid out-of-pocket** — distinct from childcare
  *subsidy* received.
* **Work-related transportation expenses** — small but published.
* **Disambiguated transfer income** — ACS bundles "other income" (OIP)
  whereas CPS-ASEC reports SNAP/TANF/SSI cleanly. Phase 4 take-up
  imputation fills this from administrative caseload, but a CPS donor
  match is the canonical alternative.

The framework here is the standard k-nearest-neighbor donor-match used
by TRIM3, the SPM Research File, and PolicyEngine US's "Enhanced CPS":

  1. Both donors (CPS-ASEC) and recipients (ACS) are projected to a
     common feature space via ``match_vars`` (age, family size,
     income tier, etc.).
  2. Each recipient finds its K nearest donors by scaled Euclidean
     distance.
  3. Donor variables are averaged across the K nearest, with optional
     stratification (e.g. nearest donors *within the same income tier*).

Phase 8 ships:

  * Generic :class:`DonorMatcher`.
  * MOOP imputation (:func:`impute_moop`) as the first concrete use
    case, with a small bundled synthetic CPS-style donor fixture.

Replace the bundled donor fixture with a real CPS-ASEC SPM Research
File slice when promoting to production. The API contract here
(``donors_df`` + ``match_vars`` + ``donor_vars``) is stable.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd

from tax_modeler.errors import ConfigError, DataValidationError, MissingDataError


_PACKAGE_ROOT = Path(__file__).resolve().parents[1]
# Phase 9a: real Hawaii CPS-ASEC slice (~2,575 person-records). Generated by
# ``scripts/build_cps_asec_slice.py``. Falls back to the synthetic donor CSV
# when the real parquet isn't present (CI on a fresh clone).
_REAL_CPS_HI_PARQUET = _PACKAGE_ROOT / "data" / "cps_donor" / "cps_asec_hawaii.parquet"
_DEFAULT_CPS_DONOR_CSV = _PACKAGE_ROOT / "data" / "cps_donor" / "cps_moop_donors.csv"


@dataclass
class DonorMatcher:
    """K-nearest-neighbor donor-matching imputation engine.

    Attributes
    ----------
    donors_df:
        Donor frame (e.g. CPS-ASEC sample). Must contain every column
        in ``match_vars`` and ``donor_vars``.
    match_vars:
        Numeric features used for distance computation. Each is
        z-score-normalized so heterogeneously-scaled features (age,
        income, household size) get equal weight by default.
    donor_vars:
        Columns whose donor values are imputed onto recipients.
    k:
        Number of nearest neighbors. Default 5 — TRIM3 standard.
    feature_weights:
        Optional ``{match_var -> weight}`` dict to up- or down-weight
        specific features in the distance metric. Default: equal.
    """

    donors_df: pd.DataFrame
    match_vars: Sequence[str]
    donor_vars: Sequence[str]
    k: int = 5
    feature_weights: Mapping[str, float] = field(default_factory=dict)

    def __post_init__(self) -> None:
        missing = [c for c in list(self.match_vars) + list(self.donor_vars)
                   if c not in self.donors_df.columns]
        if missing:
            raise DataValidationError(
                f"DonorMatcher: donors_df is missing columns: {missing}",
                missing_columns=missing,
            )
        if self.k < 1:
            raise ConfigError(f"DonorMatcher.k must be >= 1; got {self.k}")
        # Pre-compute z-score scaling on match_vars
        d = self.donors_df[list(self.match_vars)].astype(float).to_numpy()
        self._mean = d.mean(axis=0)
        self._std = np.where(d.std(axis=0) > 0, d.std(axis=0), 1.0)
        self._donor_features = (d - self._mean) / self._std
        # Apply feature weights
        weights = np.array([
            float(self.feature_weights.get(v, 1.0)) for v in self.match_vars
        ])
        self._donor_features = self._donor_features * weights
        self._weights = weights
        self._donor_values = self.donors_df[list(self.donor_vars)].astype(float).to_numpy()

    def impute(self, recipients_df: pd.DataFrame) -> pd.DataFrame:
        """Add ``donor_vars`` columns to ``recipients_df`` via k-NN matching.

        Returns a copy of ``recipients_df``. Existing columns of the
        same name are preserved (idempotent — call twice safely).
        """
        out = recipients_df.copy()
        missing = [c for c in self.match_vars if c not in out.columns]
        if missing:
            raise DataValidationError(
                f"impute(): recipients_df missing match_vars: {missing}",
                missing_columns=missing,
            )

        r = out[list(self.match_vars)].astype(float).to_numpy()
        r_features = ((r - self._mean) / self._std) * self._weights

        # Pairwise distances (recipients × donors). For ~50 recipients
        # and ~200 donors this is trivial; switch to sklearn KDTree if
        # the recipient frame ever exceeds ~10k rows.
        # Distance² = ||r_i - d_j||²
        # Expanded: ||r||² + ||d||² - 2·(r·d)
        donors = self._donor_features
        r_norms = (r_features ** 2).sum(axis=1, keepdims=True)
        d_norms = (donors ** 2).sum(axis=1)
        cross = r_features @ donors.T
        d2 = r_norms + d_norms - 2.0 * cross

        k = min(self.k, len(self.donors_df))
        nearest_idx = np.argpartition(d2, k - 1, axis=1)[:, :k]

        for j, var in enumerate(self.donor_vars):
            donor_col = self._donor_values[:, j]
            picked = donor_col[nearest_idx]    # (n_recipients, k)
            imputed = picked.mean(axis=1)
            target_col = f"{var}_imputed" if var in out.columns else var
            out[target_col] = imputed

        return out


# ---------------------------------------------------------------------------
# MOOP imputation (Phase 8 concrete use case)
# ---------------------------------------------------------------------------


def _load_default_cps_donors() -> pd.DataFrame:
    """Load the default CPS-style donor frame.

    Preference order:
      1. **Real Hawaii CPS-ASEC slice** at ``data/cps_donor/cps_asec_hawaii.parquet``
         (built by ``scripts/build_cps_asec_slice.py``). Production-grade.
      2. **Synthetic donor CSV** at ``data/cps_donor/cps_moop_donors.csv``
         (built by ``tests/tax_modeler/fixtures/_build_cps_donor_fixture.py``).
         CI-compatible fallback when the real slice isn't present.
    """
    if _REAL_CPS_HI_PARQUET.exists():
        donors = pd.read_parquet(_REAL_CPS_HI_PARQUET)
        # Real CPS slice has the columns we need but the variable mapping
        # done in build_cps_asec_slice.py already renames to: age, hh_size,
        # income, moop, childcare_expense, work_expense, weight. The donor
        # columns used by impute_moop / impute_childcare_expense /
        # impute_work_expense look these up directly.
        return donors
    if _DEFAULT_CPS_DONOR_CSV.exists():
        return pd.read_csv(_DEFAULT_CPS_DONOR_CSV)
    raise MissingDataError(
        f"No CPS donor fixture found. Looked for:\n"
        f"  (1) real slice at {_REAL_CPS_HI_PARQUET} — generate via "
        "scripts/build_cps_asec_slice.py\n"
        f"  (2) synthetic CSV at {_DEFAULT_CPS_DONOR_CSV} — generate via "
        "tests/tax_modeler/fixtures/_build_cps_donor_fixture.py",
        path=_REAL_CPS_HI_PARQUET,
    )


def impute_moop(
    units: pd.DataFrame,
    *,
    donors_df: Optional[pd.DataFrame] = None,
    k: int = 5,
    out_col: str = "moop_amount",
) -> pd.DataFrame:
    """Impute medical out-of-pocket (MOOP) onto tax units via CPS donor match.

    Match features (z-scored): primary age, household size, income.
    Donor variable: ``moop_amount`` from the CPS-ASEC SPM Research File
    (or the bundled synthetic donor fixture).

    Returns a copy of ``units`` with ``out_col`` populated. The new
    column can be passed to :func:`tax_modeler.poverty.compute_spm_resources`
    as ``moop_col=out_col`` to remove MOOP from SPM resources, removing
    the ~1-2 pp poverty undercount documented in the Phase 2 SPM module.
    """
    df = units.copy()
    # Build recipient match frame directly (avoid name conflict with the
    # existing ``income`` column on ``df``)
    is_joint = (df["filing_status"] == "married_filing_jointly").to_numpy()
    n_dep = df["num_dependents"].fillna(0).astype(int).to_numpy()
    age_arr = (
        df["primary_agep"].fillna(0).astype(float).to_numpy()
        if "primary_agep" in df.columns
        else np.full(len(df), 35.0)
    )
    rec_for_match = pd.DataFrame({
        "age": age_arr,
        "hh_size": 1 + is_joint.astype(int) + n_dep,
        "income": df["income"].fillna(0).astype(float).clip(lower=0).to_numpy(),
    }, index=df.index)

    donors = donors_df if donors_df is not None else _load_default_cps_donors()
    matcher = DonorMatcher(
        donors_df=donors,
        match_vars=("age", "hh_size", "income"),
        donor_vars=("moop",),
        k=k,
    )
    imputed = matcher.impute(rec_for_match)

    df[out_col] = imputed["moop"].clip(lower=0).to_numpy()
    return df


def _impute_via_donor_match(
    units: pd.DataFrame,
    *,
    donor_var: str,
    donors_df: Optional[pd.DataFrame],
    k: int,
    out_col: str,
) -> pd.DataFrame:
    """Internal helper: build the recipient match frame and run a single-var impute."""
    df = units.copy()
    is_joint = (df["filing_status"] == "married_filing_jointly").to_numpy()
    n_dep = df["num_dependents"].fillna(0).astype(int).to_numpy()
    age_arr = (
        df["primary_agep"].fillna(0).astype(float).to_numpy()
        if "primary_agep" in df.columns
        else np.full(len(df), 35.0)
    )
    rec_for_match = pd.DataFrame({
        "age": age_arr,
        "hh_size": 1 + is_joint.astype(int) + n_dep,
        "income": df["income"].fillna(0).astype(float).clip(lower=0).to_numpy(),
    }, index=df.index)
    donors = donors_df if donors_df is not None else _load_default_cps_donors()
    if donor_var not in donors.columns:
        raise DataValidationError(
            f"donors_df missing column {donor_var!r} (have: {list(donors.columns)})",
            missing_columns=[donor_var],
        )
    matcher = DonorMatcher(
        donors_df=donors,
        match_vars=("age", "hh_size", "income"),
        donor_vars=(donor_var,),
        k=k,
    )
    imputed = matcher.impute(rec_for_match)
    df[out_col] = imputed[donor_var].clip(lower=0).to_numpy()
    return df


def impute_childcare_expense(
    units: pd.DataFrame,
    *,
    donors_df: Optional[pd.DataFrame] = None,
    k: int = 5,
    out_col: str = "childcare_expense_amount",
) -> pd.DataFrame:
    """Impute out-of-pocket childcare expense onto units via CPS donor match.

    Donor variable: CPS-ASEC ``SPM_CHILDCAREXPNS`` (renamed
    ``childcare_expense`` in :func:`scripts/build_cps_asec_slice.py`).
    Match features: primary age, household size, income.

    Note this is the *parent-paid* expense (subtracted from SPM resources),
    distinct from the *childcare subsidy received* (column
    ``childcare_amount`` populated by ``benefits.childcare``). When both
    are present, SPM resources subtract the expense and add the subsidy.
    """
    return _impute_via_donor_match(
        units, donor_var="childcare_expense",
        donors_df=donors_df, k=k, out_col=out_col,
    )


def impute_work_expense(
    units: pd.DataFrame,
    *,
    donors_df: Optional[pd.DataFrame] = None,
    k: int = 5,
    out_col: str = "work_expense_amount",
) -> pd.DataFrame:
    """Impute work-related expense (commute, etc.) onto units via CPS donor match.

    Donor variable: CPS-ASEC ``SPM_CAPWKCCXPNS`` minus
    ``SPM_CHILDCAREXPNS`` (the residual work-only piece) — computed as
    ``work_expense`` in the bundled HI slice.
    """
    return _impute_via_donor_match(
        units, donor_var="work_expense",
        donors_df=donors_df, k=k, out_col=out_col,
    )


__all__ = [
    "DonorMatcher",
    "impute_moop",
    "impute_childcare_expense",
    "impute_work_expense",
]
